spring.application.name=CareSync
# Database connection (Cloud SQL via Cloud SQL Connector)

#LIVE
spring.datasource.url=jdbc:postgresql://google/postgres?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=care-sync-467705:us-central1:care-sync-postgres-db
spring.datasource.username=postgres
spring.datasource.password=Bolt@1105
spring.datasource.driver-class-name=org.postgresql.Driver
google.cloud.credentials.path=/secrets/service-account.json

#DEVLEOPMENT
#spring.datasource.url=jdbc:postgresql://localhost:5432/docai_db
#spring.datasource.username=postgres
#spring.datasource.password=your_password
#google.cloud.credentials.path=src/main/resources/credentials/service-account.json

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server port (optional)
server.port=8080

# Google Cloud
google.cloud.credentials.location=classpath:credentials/service-account.json
google.documentai.project-id=care-sync-467705
google.documentai.location=us
google.documentai.processor-id=6adda2a5acbf6f8d
gemini.api-key=${GEMINI_API_KEY}

# Increase file upload size limits
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=30MB

#Email
spring.mail.host=smtp.mailgun.org
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=noreply@mg.hinetics.lk

#Time
spring.jackson.time-zone=UTC
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
